-- Schema for Solar & Burji (Egg Center) app

CREATE TABLE IF NOT EXISTS solar_daily (
  id INT AUTO_INCREMENT PRIMARY KEY,
  reading_date DATE NOT NULL UNIQUE,
  import_kwh DECIMAL(10,3) NOT NULL DEFAULT 0, -- Energy imported from grid (kWh)
  export_kwh DECIMAL(10,3) NOT NULL DEFAULT 0, -- Energy exported to grid (kWh)
  generation_kwh DECIMAL(10,3) NOT NULL DEFAULT 0, -- Energy generated by solar (kWh)
  notes VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX (reading_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sales (
  id INT AUTO_INCREMENT PRIMARY KEY,
  txn_date DATE NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  payment_method ENUM('cash','online') NOT NULL,
  note VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX (txn_date),
  INDEX (payment_method)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS borrowings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  txn_date DATE NOT NULL,
  customer_name VARCHAR(120) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  is_repayment TINYINT(1) NOT NULL DEFAULT 0, -- 0 = borrowing (credit extended), 1 = repayment received
  note VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX (txn_date),
  INDEX (customer_name),
  INDEX (is_repayment)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
